pipeline {
    agent any
    stages {
        stage('startup') {
           steps {
                sh '''
		echo "Started Jenkins pipeline"
		'''
            }    
        }
		stage('ansible-playbook') {
           steps {
                sh '''
		ansible-playbook -i /var/jenkins_home/workspace/ansible-playbook/ansible/inventory /var/jenkins_home/workspace/ansible-playbook/ansible/playbook.yaml
		'''
            }    
        }    
    }
}

