pipeline {
    agent any
    stages {
        stage('startup') {
           steps {
                sh '''
		echo "Started Jenkins pipeline"
		'''
            }    
        }
	stage('ansible-playbook') {
           steps {
                sh '''
		ansible-playbook -i ansible/inventory ansible/playbook.yaml  -vvvv
		'''
            }    
        }    
    }
}

