- name: copy file  to worker
  hosts: worker
  become: true
  tasks:

    - name: copy a file
      copy:
        src: /var/jenkins_home/workspace/ansible-playbook/ansible/compose.yaml
        dest: /home/compose.yaml

    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present

    - name: Deploy stack from a compose file
      docker_stack:
        state: present
        name: Jenkins
        compose:
          - /home/compose.yaml
