- name: copy file  to worker
  hosts: worker
  become: true
  tasks:
    - name: Touch a file, using symbolic modes to set the   permissions (equivalent to 0644)
      ansible.builtin.file:
        path: /home/compose.yaml
        state: touch
    - name: copy a file
      copy:
        src: ansible/compose.yaml
        dest: /home/compose.yaml

    - name: Init a new swarm with default parameters
      community.docker.docker_swarm:
        state: present

    - name: Deploy stack from a compose file
      docker_stack:
        state: present
        name: Jenkins
        compose:
          - /home/compose.yaml
